"""
MVT Notification API Lambda (EV5-07)
GET /api/notifications — Retrieve notifications for current user
PUT /api/notifications/{id}/read — Mark notification as read
POST /api/notifications/dismiss-all — Dismiss all notifications

Notifications are generated by threshold breaches detected by processing Lambdas.
Stored in dashboard-state under dashboard='notifications'.

Trigger: API Gateway HTTP
"""

import json
import os
import logging
import time
from datetime import datetime, timedelta
from decimal import Decimal
import boto3
from boto3.dynamodb.conditions import Key

logger = logging.getLogger()
logger.setLevel(logging.INFO)

dynamodb = boto3.resource('dynamodb')

DASHBOARD_STATE_TABLE = os.environ.get('DASHBOARD_STATE_TABLE', 'mvt-dashboard-state')

# Threshold definitions for generating notifications
THRESHOLDS = {
    'distress_index': {'warning': 30, 'critical': 50, 'label': 'Distress Index'},
    'trigger_probability': {'warning': 15, 'critical': 25, 'label': 'Trigger Probability'},
    'contagion_risk': {'warning': 60, 'critical': 75, 'label': 'Contagion Risk'},
    'vix_level': {'warning': 25, 'critical': 35, 'label': 'VIX Level'},
}


class DecimalEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, Decimal):
            return float(obj)
        return super().default(obj)


def get_notifications(limit=50):
    """Get recent notifications from dashboard-state."""
    table = dynamodb.Table(DASHBOARD_STATE_TABLE)
    try:
        response = table.query(
            KeyConditionExpression=Key('dashboard').eq('notifications'),
            ScanIndexForward=False,
            Limit=limit
        )
        items = response.get('Items', [])
        notifications = []
        for item in items:
            notifications.append({
                'id': item.get('panel', ''),
                'type': item.get('notification_type', 'info'),
                'severity': item.get('severity', 'info'),
                'title': item.get('title', ''),
                'message': item.get('message', ''),
                'kpi': item.get('kpi', ''),
                'value': float(item.get('value', 0)),
                'threshold': float(item.get('threshold', 0)),
                'read': item.get('read', False),
                'timestamp': item.get('timestamp', ''),
            })
        return notifications
    except Exception as e:
        logger.error(f"Error fetching notifications: {e}")
        return []


def mark_read(notification_id):
    """Mark a notification as read."""
    table = dynamodb.Table(DASHBOARD_STATE_TABLE)
    try:
        table.update_item(
            Key={'dashboard': 'notifications', 'panel': notification_id},
            UpdateExpression='SET #r = :val',
            ExpressionAttributeNames={'#r': 'read'},
            ExpressionAttributeValues={':val': True}
        )
        return True
    except Exception as e:
        logger.error(f"Error marking notification read: {e}")
        return False


def dismiss_all():
    """Mark all notifications as read."""
    table = dynamodb.Table(DASHBOARD_STATE_TABLE)
    try:
        response = table.query(
            KeyConditionExpression=Key('dashboard').eq('notifications'),
            FilterExpression='#r = :false_val',
            ExpressionAttributeNames={'#r': 'read'},
            ExpressionAttributeValues={':false_val': False}
        )
        for item in response.get('Items', []):
            table.update_item(
                Key={'dashboard': 'notifications', 'panel': item['panel']},
                UpdateExpression='SET #r = :val',
                ExpressionAttributeNames={'#r': 'read'},
                ExpressionAttributeValues={':val': True}
            )
        return True
    except Exception as e:
        logger.error(f"Error dismissing all notifications: {e}")
        return False


def generate_threshold_notifications():
    """Check current KPI values against thresholds and create notifications."""
    table = dynamodb.Table(DASHBOARD_STATE_TABLE)
    new_notifications = []

    # Check composite vulnerability score
    try:
        response = table.get_item(Key={'dashboard': 'composite', 'panel': 'vulnerability_score'})
        if 'Item' in response:
            item = response['Item']
            distress = float(item.get('distress_index', 0))
            trigger = float(item.get('trigger_probability', 0))
            contagion = float(item.get('contagion_risk', 0))

            for kpi_name, value in [('distress_index', distress), ('trigger_probability', trigger), ('contagion_risk', contagion)]:
                thresholds = THRESHOLDS.get(kpi_name, {})
                if value >= thresholds.get('critical', float('inf')):
                    new_notifications.append({
                        'type': 'threshold_breach',
                        'severity': 'critical',
                        'kpi': kpi_name,
                        'value': value,
                        'threshold': thresholds['critical'],
                        'title': f"{thresholds.get('label', kpi_name)} CRITICAL",
                        'message': f"{thresholds.get('label', kpi_name)} at {value:.2f} exceeds critical threshold of {thresholds['critical']}",
                    })
                elif value >= thresholds.get('warning', float('inf')):
                    new_notifications.append({
                        'type': 'threshold_breach',
                        'severity': 'warning',
                        'kpi': kpi_name,
                        'value': value,
                        'threshold': thresholds['warning'],
                        'title': f"{thresholds.get('label', kpi_name)} Warning",
                        'message': f"{thresholds.get('label', kpi_name)} at {value:.2f} exceeds warning threshold of {thresholds['warning']}",
                    })
    except Exception as e:
        logger.warning(f"Error checking thresholds: {e}")

    # Write new notifications
    timestamp = datetime.utcnow().isoformat()
    for notif in new_notifications:
        notif_id = f"notif_{notif['kpi']}_{int(time.time())}"
        try:
            table.put_item(Item={
                'dashboard': 'notifications',
                'panel': notif_id,
                'notification_type': notif['type'],
                'severity': notif['severity'],
                'kpi': notif['kpi'],
                'value': Decimal(str(round(notif['value'], 4))),
                'threshold': Decimal(str(notif['threshold'])),
                'title': notif['title'],
                'message': notif['message'],
                'read': False,
                'timestamp': timestamp,
                'ttl': int(time.time()) + 7 * 86400,  # 7-day TTL
            })
        except Exception as e:
            logger.error(f"Error writing notification: {e}")

    return new_notifications


def handler(event, context):
    """Main Lambda handler."""
    logger.info(f"Notification API request: {json.dumps(event, default=str)}")

    method = event.get('requestContext', {}).get('http', {}).get('method', 'GET')
    raw_path = event.get('rawPath', '')

    headers = {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET,PUT,POST,OPTIONS',
    }

    if method == 'OPTIONS':
        return {'statusCode': 200, 'headers': headers, 'body': ''}

    if method == 'GET' and '/notifications' in raw_path:
        # Check thresholds and generate any new notifications
        generate_threshold_notifications()
        notifications = get_notifications()
        unread_count = sum(1 for n in notifications if not n.get('read'))

        return {
            'statusCode': 200,
            'headers': headers,
            'body': json.dumps({
                'notifications': notifications,
                'unread_count': unread_count,
                'total': len(notifications),
            }, cls=DecimalEncoder)
        }

    if method == 'PUT' and '/read' in raw_path:
        # Extract notification ID
        parts = raw_path.strip('/').split('/')
        notif_id = parts[-2] if len(parts) >= 2 else ''
        if mark_read(notif_id):
            return {'statusCode': 200, 'headers': headers, 'body': json.dumps({'success': True})}
        return {'statusCode': 500, 'headers': headers, 'body': json.dumps({'error': 'Failed to mark read'})}

    if method == 'POST' and '/dismiss-all' in raw_path:
        if dismiss_all():
            return {'statusCode': 200, 'headers': headers, 'body': json.dumps({'success': True})}
        return {'statusCode': 500, 'headers': headers, 'body': json.dumps({'error': 'Failed to dismiss'})}

    return {
        'statusCode': 404,
        'headers': headers,
        'body': json.dumps({'error': 'Not found'})
    }
